// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EgyDynamics2.Models;

[Table("الموظف")]
public partial class الموظف
{
    [Key]
    [Column("كود الموظف")]
    public int كودالموظف { get; set; }

    [Column("اسم الموظف")]
    [StringLength(255)]
    public string اسمالموظف { get; set; }

    [Column("اسم المستخدم")]
    [StringLength(20)]
    public string اسمالمستخدم { get; set; }

    [Column("كلمة المرور")]
    [StringLength(20)]
    public string كلمةالمرور { get; set; }

    [InverseProperty("اخرتعديلNavigation")]
    public virtual ICollection<العميل> العميلاخرتعديلNavigations { get; set; } = new List<العميل>();

    [InverseProperty("ادخالبواسطةNavigation")]
    public virtual ICollection<العميل> العميلادخالبواسطةNavigations { get; set; } = new List<العميل>();

    [InverseProperty("اخرتعديلNavigation")]
    public virtual ICollection<مكالمهالعميل> مكالمهالعميلاخرتعديلNavigations { get; set; } = new List<مكالمهالعميل>();

    [InverseProperty("ادخالبواسطهNavigation")]
    public virtual ICollection<مكالمهالعميل> مكالمهالعميلادخالبواسطهNavigations { get; set; } = new List<مكالمهالعميل>();

    [InverseProperty("الموظفNavigation")]
    public virtual ICollection<مكالمهالعميل> مكالمهالعميلالموظفNavigations { get; set; } = new List<مكالمهالعميل>();
}