// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EgyDynamics2.Models;

[Table("العميل")]
public partial class العميل
{
    [Key]
    [Column("كود العميل")]
    public int كودالعميل { get; set; }

    [Column("اسم العميل")]
    [StringLength(255)]
    public string اسمالعميل { get; set; }

    [Column("محل الاقامة")]
    [StringLength(255)]
    public string محلالاقامة { get; set; }

    [StringLength(255)]
    public string توصيف { get; set; }

    [StringLength(255)]
    public string الوظيفة { get; set; }

    [Column("ادخال بواسطة")]
    public int? ادخالبواسطة { get; set; }

    [Column("تاريخ الادخال")]
    public DateTime? تاريخالادخال { get; set; }

    [Column("اخر تعديل")]
    public int? اخرتعديل { get; set; }

    [Column("اخر تعديل في")]
    public DateTime? اخرتعديلفي { get; set; }

    [Column("رجل المبيعات")]
    [StringLength(255)]
    public string رجلالمبيعات { get; set; }

    [Column("مصدر العميل")]
    [StringLength(255)]
    public string مصدرالعميل { get; set; }

    [Column("تصنيف العميل")]
    [StringLength(255)]
    public string تصنيفالعميل { get; set; }

    [StringLength(20)]
    public string موبايل { get; set; }

    [StringLength(20)]
    public string تليفون1 { get; set; }

    [StringLength(20)]
    public string تليفون2 { get; set; }

    [StringLength(20)]
    public string واتس { get; set; }

    [StringLength(50)]
    public string جنسية { get; set; }

    [StringLength(50)]
    public string الايميل { get; set; }

    [ForeignKey("اخرتعديل")]
    [InverseProperty("العميلاخرتعديلNavigations")]
    public virtual الموظف اخرتعديلNavigation { get; set; }

    [ForeignKey("ادخالبواسطة")]
    [InverseProperty("العميلادخالبواسطةNavigations")]
    public virtual الموظف ادخالبواسطةNavigation { get; set; }

    [InverseProperty("كودالعميلNavigation")]
    public virtual ICollection<مكالمهالعميل> مكالمهالعميلs { get; set; } = new List<مكالمهالعميل>();
}