// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EgyDynamics2.Models;

[Table("مكالمه العميل")]
public partial class مكالمهالعميل
{
    [Key]
    [Column("كود مكالمة العميل")]
    public int كودمكالمةالعميل { get; set; }

    [StringLength(255)]
    public string التوصيف { get; set; }

    //[Column("مدة المكالمه")]
    //public int? مدةالمكالمه { get; set; }

    public DateTime? التاريخ { get; set; }

    [StringLength(255)]
    public string المشروع { get; set; }

    public int? الموظف { get; set; }

    [Column("هل تمت")]
    public bool? هلتمت { get; set; }

    [Column("نوع المكالمه")]
    [StringLength(255)]
    public string نوعالمكالمه { get; set; }

    [Column("هل وارد")]
    public bool? هلوارد { get; set; }

    [Column("ادخال بواسطه")]
    public int? ادخالبواسطه { get; set; }

    [Column("تاريخ الادخال")]
    public DateTime? تاريخالادخال { get; set; }

    [Column("اخر تعديل في")]
    public DateTime? اخرتعديلفي { get; set; }

    [Column("اخر تعديل")]
    public int? اخرتعديل { get; set; }

    [Column("كود العميل")]
    public int? كودالعميل { get; set; }

    [ForeignKey("اخرتعديل")]
    [InverseProperty("مكالمهالعميلاخرتعديلNavigations")]
    public virtual الموظف اخرتعديلNavigation { get; set; }

    [ForeignKey("ادخالبواسطه")]
    [InverseProperty("مكالمهالعميلادخالبواسطهNavigations")]
    public virtual الموظف ادخالبواسطهNavigation { get; set; }

    [ForeignKey("الموظف")]
    [InverseProperty("مكالمهالعميلالموظفNavigations")]
    public virtual الموظف الموظفNavigation { get; set; }

    [ForeignKey("كودالعميل")]
    [InverseProperty("مكالمهالعميلs")]
    public virtual العميل كودالعميلNavigation { get; set; }
}